add run script idea

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,15 +1,5 @@
 #!/bin/bash
 
-if [[ ! -d "./obj/" ]]
-then
-    mkdir ./obj/
-fi
-
-if [[ ! -d "./build/" ]]
-then
-    mkdir ./build/
-fi
-
 if [[ ! -d "./bin/" ]]
 then
     mkdir ./bin/
@@ -22,46 +12,122 @@ else
     build=$1
 fi
 
-if [[ $build = "asan" ]] || [[ $build = "debug" ]] || [[ $build = "release" ]]
-then
+args_always="-DBUILD_LINUX \
+-Iinclude/ \
+-std=c99 \
+-I/usr/include/ \
+-Ivendor/imgsurf/include/ \
+-Ivendor/imgsurf/vendor/datasurf/include/ \
+-Ivendor/imgsurf/vendor/datasurf/vendor/puddle/include/ \
+vendor/imgsurf/vendor/datasurf/src/datasurf_formats.c \
+vendor/imgsurf/vendor/datasurf/src/datasurf_algo_deflate.c \
+vendor/imgsurf/vendor/datasurf/vendor/puddle/src/string_view.c \
+vendor/imgsurf/vendor/datasurf/vendor/puddle/src/linux_pd_path.c \
+-Wextra -Wall -Wpedantic -Wconversion -Wshadow -Wsign-compare -Wtype-limits -Wunused
+-fPIC"
 
-    if [[ -f "./vendor/imgsurf/run" ]]
+args_common="src/river3Dcommon.c \
+-c"
+
+args_software="src/linux_river3Dsoftware.c \
+./vendor/imgsurf/src/imgsurf_main.c \
+./vendor/imgsurf/src/imgsurf_format_bmp.c \
+./vendor/imgsurf/src/imgsurf_format_qoi.c \
+./vendor/imgsurf/src/imgsurf_format_png.c \
+-Lbin/$build/ \
+-lriver3Dcommon \
+-shared \
+-fuse-ld=mold"
+
+args_release="-O2"
+
+args_debug="-DDEBUG -g -O0"
+
+args_asan="$args_debug -DASAN \
+-fsanitize=address,leak,undefined \
+-fno-omit-frame-pointer \
+-static-libasan \
+-O0"
+
+function compile()
+{
+    echo "identifying a compiler..."
+
+    clang --version > /dev/null
+    if [[ $? = 0 ]]
     then
-        pushd ./vendor/imgsurf/ > /dev/null
-        ./run $build --compile-only
-        if [[ $? != 0 ]]
-        then
-            echo -e "\033[31m\nERROR: failed to compile imgsurf.\033[0m"
-            exit -1
-        fi
-        popd > /dev/null
+        echo "found clang."
+        compiler="clang"
     else
-        echo -e "\033[31m\nERROR: can't find imgsurf's run script.\033[0m"
+        gcc --version > /dev/null
+        if [[ $? = 0 ]]
+        then
+            compiler="gcc"
+        else
+            echo -e "\033[31m\nERROR: no suitable compiler found.\n\033[0m"
+        fi
+    fi
+
+    if [[ ! -d ./bin/$build ]]
+    then
+        mkdir ./bin/$build
     fi
 
     echo ""
-    echo -e "\033[36mcompiling river3D...\033[0m"
+    echo -e "\033[36mcompiling river3Dcommon...\033[0m"
     echo ""
-    premake5 gmake
+    echo "compiling $build build with the following command:"
+    echo "$compiler $1 $args_common"
 
-    pushd ./build/ > /dev/null
-    make config=$build\_linux
+    $($compiler $1 $args_common)
+    if [[ $? != 0 ]]
+    then
+        echo -e "\033[31m\nERROR: $compiler failed to compile river3Dcommon.\n\033[0m"
+        exit -1
+    fi
+
+    echo ""
+    echo -e "\033[36mcreating static libary libriver3Dcommon.a...\033[0m"
+    echo ""
+    ar rcs ./bin/$build/libriver3Dcommon.a river3D_util.o string_view.o \
+    river3Dcommon_main.o linux_river3Dcommon.o linux_pd_path.o
+    if [[ $? != 0 ]]
+    then
+        echo -e "\033[31m\nERROR: ar failed to create static library.\n\033[0m"
+        exit -1
+    fi
+
+    echo ""
+    echo -e "\033[36mcompiling river3Dsoftware...\033[0m"
+    echo ""
+    echo "compiling $build build with the following command:"
+    echo "$compiler $1 $args_software"
+
+    $($compiler $1 $args_software)
+    if [[ $? != 0 ]]
+    then
+        echo -e "\033[31m\nERROR: $compiler failed to compile river3Dsoftware.\n\033[0m"
+        exit -1
+    fi
+    mv ./a.out ./bin/$build/libriver3Dsoftware.so
+}
+
+if [[ $build = "release" ]]
+then
+    compile "$args_always $args_release"
+else
+if [[ $build = "debug" ]]
+then
+    compile "$args_always $args_debug"
+else
+if [[ $build = "asan" ]]
+then
+    compile "$args_always $args_asan"
 else
     echo -e "\033[31m\nERROR: invalid make config: $build.\033[0m"
-    exit -2;
+    exit 3;
 fi
-
-if [[ $? != 0 ]]
-then
-    echo -e "\033[31m\nERROR: failed to compile river3D.\n\033[0m"
-    exit -1
+fi
 fi
 
 echo -e "\n"
-
-if [[ $2 = "--compile-only" ]]
-then
-    exit 0
-fi
-
-popd > /dev/null
